# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        OC\UserBundle\Entity\User: sha512
        # OC\UserBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:         [ROLE_AUTEUR, ROLE_MODERATEUR]
        ROLE_SUPER_ADMIN:   [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        main:
            id:             fos_user.user_provider.username
#            entity:
#                class:    OC\UserBundle\Entity\User
#                property: username

    firewalls:
        dev:
            pattern:        ^/(_(profiler|wdt)|css|images|js)/
            security:       false
            
        main:
            pattern:        ^/
            anonymous:      true
#            provider: in_memory
            provider:       main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
#                login_path: login
#                check_path: login_check
            logout:
                path:       fos_user_security_logout
#                path:   logout
                target:     /platform
            remember_me:
                key:        %secret%

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN, requires_channel: https }

    
    
    
    
    
    
    
    
    
    
    
#    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
#    providers:
#        in_memory:
#            memory: ~
#
#    firewalls:
#        # disables authentication for assets and the profiler, adapt it according to your needs
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        main:
#            anonymous: ~
#            # activate different ways to authenticate
#
#            # http_basic: ~
#            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate
#
#            # form_login: ~
#            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
#
#   access_control:
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

