services:
    oc_platform.antispam:
        class:     OC\PlatformBundle\Antispam\OCAntispam
        arguments: [@mailer, 50]
        calls:
            - [ setLocale, [ %locale% ] ]
        tags:
            - { name: twig.extension }
        
    oc_platform.doctrine.notification:
        class: OC\PlatformBundle\DoctrineListener\ApplicationNotification
        arguments: [@mailer]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            
    oc_platform.ckeditor:
        class: OC\PlatformBundle\Form\Type\CKeditorType
        tags:
            - { name: form.type, alias: ckeditor }
            
    oc_platform.beta.html:
        class: OC\PlatformBundle\Beta\BetaHTML
         
    oc_platform.beta.listener:
        class: OC\PlatformBundle\Beta\BetaListener
        arguments: [@oc_platform.beta.html, "2016-06-20"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: processBeta }
            
    oc_platform.censorship_processor:
        class:     OC\PlatformBundle\Bigbrother\CensorshipProcessor
        arguments: [@mailer]

    oc_platform.censorship_listener:
        class:     OC\PlatformBundle\Bigbrother\CensorshipListener
        arguments: [@oc_platform.censorship_processor, [1, 2, 3]]
        tags:
            - { name: kernel.event_listener, event: oc_platform.bigbrother.post_message, method: processMessage }